<script>
    try {
        // 数値に対して文字列のメソッドであるtoUpperCaseを呼んだ場合
        const num = 1;
        num.toUpperCase(); // TypeErrorが発生
        // 存在しない変数val2を参照した場合
        let val1 = val2 + 1; // ReferenceErrorが発生
    } catch (error) {
        if (error instanceof TypeError) {
            console.log("TypeErrorが発生したときの処理");
        } else if (error instanceof ReferenceError) {
            console.log("ReferenceErrorが発生したときの処理");
        }
    }
</script>