<script>
    function promiseFactory(count) {
        return new Promise((resolve, reject) => {
            setTimeout(() => {
                count++;
                console.log(`${count}回目のコールです。時刻：[${new Date().toTimeString()}]`);
                if (count === 3) { // 3回目のコールでエラー
                    reject(count);
                } else {
                    resolve(count);
                }
            }, 1000);
        });
    }
    promiseFactory(0)
        .then(count => { return promiseFactory(count); })
        .then(count => { return promiseFactory(count); })
        .then(count => { return promiseFactory(count); })
        .then(count => { return promiseFactory(count); })
        .catch(errorCount => {
            console.error(`エラーに飛びました。現在のカウントは ${errorCount} です。`);
        }).finally(() => {
            console.log("処理を終了します。");
        });
    // > 1回目のコールです。時刻：[16:23:19 GMT+0900 (日本標準時)]
    // > 2回目のコールです。時刻：[16:23:20 GMT+0900 (日本標準時)]
    // > 3回目のコールです。時刻：[16:23:21 GMT+0900 (日本標準時)]
    // > エラーに飛びました。現在のカウントは3です。
    // > 処理を終了します。
</script>